---
- name: Install Latex tools
  become: true
  ansible.builtin.apt:
    name:
      - texlive-latex-base
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-latex-extra
      - chktex
      - texlive-extra-utils
      - latexmk
    state: present
    update_cache: true
    cache_valid_time: 3600