---
- name: Git clone btop
  ansible.builtin.git:
    repo: https://github.com/aristocratos/btop.git
    dest: "{{ ansible_env.HOME }}/.local/src/btop"
    version: v1.3.0

- name: Compile btop
  community.general.make:
    chdir: "{{ ansible_env.HOME }}/.local/src/btop/"
    params:
      ADDFLAGS: -march=native

- name: Install btop
  become: true
  community.general.make:
    chdir: "{{ ansible_env.HOME }}/.local/src/btop/"
    target: install
