---
- name: Check if obsidian is installed
  ansible.builtin.stat:
    path: "/usr/bin/obsidian"
  register: obsidian_stat

- name: Install Obsidian from .deb
  when: not obsidian_stat.stat.exists
  become: true
  ansible.builtin.apt:
    deb: "{{ obsidian_deb_url }}"

- name: Clone git repo containing the vault
  # Repeating the condition, to avoid pulling the repo mutliple times as each execution will change
  when: not obsidian_stat.stat.exists
  ansible.builtin.git:
    repo: "{{ obsidian.git_repo }}"
    dest: "{{ obsidian.vault_dir }}"
