---
# Inspired from: https://github.com/LorenzoBettini/ansible-molecule-oh-my-zsh-example/blob/master/files/zshrc-starship

# ===== #
# Utils #
# ===== #
# Inspired from https://www.jeffgeerling.com/blog/2022/aptkey-deprecated-debianubuntu-how-fix-ansible
- name: Add eza apt repository key.
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
    dest: /etc/apt/trusted.gpg.d/eza.asc
    mode: '0644'
    force: true

- name: Add eza apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/eza.asc] http://deb.gierens.de stable main"
    state: present

- name: Install packages with apt
  become: true
  ansible.builtin.apt:
    name:
      - bat
      - curl
      - eza
      - fzf
      - git
      - htop
      - jq
      - neofetch
      - net-tools
      - ripgrep
      - tmux
      - tree
      - zsh
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Link bat to batcat (name clash on Ubuntu)
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: "{{ ansible_env.HOME }}/.local/bin/bat"
    state: link

- name: Install navi with cargo
  community.general.cargo:
    name: navi
    version: 2.20.1

- name: Install dust with cargo
  community.general.cargo:
    name: du-dust
    version: 0.8.6

- name: Install git-delta with cargo
  community.general.cargo:
    name: git-delta
    version: 0.16.5

# === #
# ZSH #
# === #
- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    depth: 1

- name: Change the default shell to Zsh
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /bin/zsh
  become: true

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: v0.7.0

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    version: 0.8.0

- name: Install fzf-tab
  ansible.builtin.git:
    repo: https://github.com/Aloxaf/fzf-tab.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/fzf-tab"
    version: c2b4aa  # Latest as of 2024/01/07

# ======== #
# Starship #
# ======== #
- name: Get starship install script
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'
  register: starship_installation_script

- name: Install starship with installation script
  become: true
  when: starship_installation_script.changed
  ansible.builtin.shell:
    cmd: /tmp/starship_install.sh --yes
    executable: /bin/sh

# ============ #
# Install font #
# ============ #
- name: Create fonts directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.fonts"
    mode: "0775"
    state: directory

- name: Download Hack
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
    dest: "{{ ansible_env.HOME }}/.fonts/"
    remote_src: true
    creates: "{{ ansible_env.HOME }}/.fonts/Hack Bold Italic Nerd Font Complete.ttf"

# ==================== #
# Gnome-terminal theme #
# ==================== #
# TODO: replace with saved dconf file
# - name: Create .local/src directory
#   ansible.builtin.file:
#     path: "{{ ansible_env.HOME }}/.local/src/"
#     mode: "0775"
#     state: directory

# - name: Install Gogh
#   ansible.builtin.git:
#     repo: https://github.com/Gogh-Co/Gogh.git
#     version: "v248"
#     dest: "{{ ansible_env.HOME }}/.local/src/gogh"

# - name: Apply Gogh theme
#   ansible.builtin.shell:
#     cmd: "{{ ansible_env.HOME }}/.local/src/gogh/installs/aci.sh"
#     executable: /bin/sh
#   environment:
#     TERMINAL: gnome-terminal
