---
- name: Add linrunnner/tlp apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: tlp
    types: [deb]
    uris: "https://ppa.launchpadcontent.net/linrunner/tlp/ubuntu"
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2042f03c5fabd0ba2ced40412b3f92f902d65eff"
    components: [main]
    suites: ["{{ ansible_distribution_release | lower }}"]
    state: present
    enabled: true

- name: Install acpi, tlp & powertop
  become: true
  ansible.builtin.apt:
    name:
      - acpi
      - powertop
      - tlp
      - tlp-rdw
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Run Dell specific optimization
  ansible.builtin.include_tasks: dell.yaml
  when: ansible_facts.chassis_vendor == "Dell Inc."

- name: Disable Bluetooth in /etc/bluetooth/main.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: '^AutoEnable=true'
    line: 'AutoEnable=false'
    state: present

# # Does not work yet, this is not valid after reboot
# # Does not work yet, this is not valid after reboot
# # Does not work yet, this is not valid after reboot
# # Does not work yet, this is not valid after reboot
# - name: Disable Docker network nic:docker0
#   become: true
#   ansible.builtin.command:
#     ifconfig docker0 down


