---
# - name: Add linrunnner/tlp repository
#   become: true
#   ansible.builtin.apt_repository:
#     repo: ppa:linrunner/tlp
#     state: present

# - name: Install acpi, tlp & powertop
#   become: true
#   ansible.builtin.apt:
#     name:
#       - acpi
#       - powertop
#       - tlp
#       - tlp-rdw
#     state: present
#     update_cache: true
#     cache_valid_time: 3600

- name: Print all available facts
  ansible.builtin.include_tasks: dell.yaml
  when: ansible_facts.chassis_vendor == "Dell Inc."

- name: Disable Bluetooth in /etc/bluetooth/main.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: '^AutoEnable=true'
    line: 'AutoEnable=false'
    state: present

- name: Disable Docker network nic:docker0
  become: true
  ansible.builtin.command:
    ifconfig docker0 down


