---
- name: Import Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install Docker tools
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Create Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add current user to the Docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true

- name: Enable systemd docker.service
  ansible.builtin.systemd_service:
    name: docker.service
    enabled: true

- name: Enable systemd containerd.service
  ansible.builtin.systemd_service:
    name: containerd.service
    enabled: true

- name: Set up log rotation in /etc/docker/daemon.json
  become: true
  lineinfile:
    path: /etc/docker/daemon.json
    line: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "5"
        }
      }
    create: true
  notify:
    - Restart Docker Service
