---
- name: Install local machine
  hosts: all
  vars_files:
    - config.yaml
  roles:
    # - rust
    # - utils-install
    # - neovim
    # - dotfiles
    # - vscode
    # - docker
    # - btop
    # ======== #
    # GPU only #
    # ======== #
    # - nvidia
    # ================ #
    # Personal machine #
    # ================ #
    # - gnome
    # - obsidian
    # - syncthing
    # - wine
    # - paperless-ngx
    - retroarch
    # - latex
    # - battery
